repos:
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: poetry run pylint json_extras/ test/
      language: system
      types: [python]
    - id: black
      name: black
      entry: poetry run black json_extras/ test/
      language: system
      types: [python]
    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: system
      types: [python]